
Get all contacts:
http://localhost:3000/contacts
https://webservices-stls.onrender.com/contacts

Get first contact:
http://localhost:3000/contacts/single?id=65a99ba97f4f82e145964bc1
https://webservices-stls.onrender.com/contacts/single?id=65a99ba97f4f82e145964bc1

Get second contact:
http://localhost:3000/contacts/single?id=65a99bdc7f4f82e14596d018
https://webservices-stls.onrender.com/contacts/single?id=65a99bdc7f4f82e14596d018

Get third contact:
http://localhost:3000/contacts/single?id=65a99c177f4f82e145977d76
https://webservices-stls.onrender.com/contacts/single?id=65a99c177f4f82e145977d76

Add a contact:
http://localhost:3000/contacts/
https://webservices-stls.onrender.com/contacts/

{
    "firstName": "new",
    "lastName": "contact",
    "email": "new@gmail.com",
    "favoriteColor": "Yellow",
    "birthday": "September 16"

}

Update a contact: 
http://localhost:3000/contacts/edit/65b53cfdca4097198b764664 (id is the id of the previous post request for adding)
https://webservices-stls.onrender.com/contacts/edit/65b540a7c151b608e8f4fcfc
{
    "firstName": "new2",
    "lastName": "contact2",
    "email": "new2@gmail.com",
    "favoriteColor": "Yellow2",
    "birthday": "September 17th"

}

Delete a contact:
http://localhost:3000/contacts/deleteOne/65b53cfdca4097198b764664
https://webservices-stls.onrender.com/contacts/deleteOne/65b540a7c151b608e8f4fcfc